export const CREATE_PROJECT = "CREATE_PROJECT"

export const RETRIVE_PROJECTS_SUCCESS = "RETRIVE_PROJECTS_SUCCESS"
export const RETRIVE_PROJECTS_REQUEST = "RETRIVE_PROJECTS_REQUEST"
export const RETRIVE_PROJECTS_FAIL = "RETRIVE_PROJECTS_FAIL"

export const DELETE_PROJECT = "DELETE_PROJECT"

export const CREATE_CONTACT = "CREATE_CONTACT"
export const RETRIVE_CONTACTS = "RETRIVE_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT"